// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login a user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login Data",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "get": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": "Registration Data",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/status": {
            "get": {
                "description": "Check login status",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Auth Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/users": {
            "get": {
                "description": "List users on the system",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            }
        },
        "/auth/users/{uid}": {
            "put": {
                "description": "Update user attributes",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/user/{uid}": {
            "delete": {
                "description": "Delete a user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/dashboard/data": {
            "get": {
                "description": "Get optimized data for the main dashboard",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["hosts"],
                "summary": "Get dashboard data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Health check",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["status"],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/hosts/by-team/": {
            "get": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["hosts"],
                "summary": "Get all hosts by team",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Team"
                            }
                        }
                    }
                }
            }
        },
        "/hosts/by-team/{tid}": {
            "get": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["hosts"],
                "summary": "Get hosts by team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "tid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Host"
                            }
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["jobs"],
                "summary": "Get all jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Job"
                            }
                        }
                    }
                }
            }
        },
        "/jobs/manager": {
            "get": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["jobs"],
                "summary": "Get job manager state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.JobStatus"
                            }
                        }
                    }
                }
            }
        },
        "/jobs/nmap/{jid}": {
            "post": {
                "description": "Upload nmap scan results",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["jobs"],
                "summary": "Upload scan results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Scan data",
                        "name": "scan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Scan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/jobs/{jobtype}/next": {
            "get": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["jobs"],
                "summary": "Get next job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job Type",
                        "name": "jobtype",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Job"
                        }
                    }
                }
            }
        },
        "/jobs/{jid}/cancel": {
            "post": {
                "description": "Cancel a running or queued job",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["jobs"],
                "summary": "Cancel a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "description": "Get all teams",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["teams"],
                "summary": "Get Teams",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Include host data",
                        "name": "include_hosts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Team"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new team",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["teams"],
                "summary": "Create team",
                "parameters": [
                    {
                        "description": "Team data",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Team"
                        }
                    }
                }
            }
        },
        "/teams/{tid}": {
            "get": {
                "description": "Get a single team with hosts",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["teams"],
                "summary": "Get Team by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "tid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Team"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing team",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["teams"],
                "summary": "Update team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "tid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Team data",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Team"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a team and its hosts",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["teams"],
                "summary": "Delete team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "tid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Host": {
            "type": "object",
            "properties": {
                "ip": { "type": "string" },
                "hostname": { "type": "string" },
                "os": { "type": "string" },
                "ports": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/models.Port" }
                },
                "team_id": { "type": "string" },
                "last_seen": { "type": "string" },
                "status": { "type": "string" }
            }
        },
        "models.Job": {
            "type": "object",
            "properties": {
                "jid": { "type": "string" },
                "type": { "type": "string" },
                "iprange": { "type": "string" },
                "status": { "type": "string" },
                "scanner": { "type": "string" },
                "tid": { "type": "string" },
                "team_name": { "type": "string" },
                "started_at": { "type": "string" },
                "completed_at": { "type": "string" },
                "hosts_found": { "type": "integer" },
                "ports_found": { "type": "integer" },
                "error_msg": { "type": "string" }
            }
        },
        "models.JobStatus": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "job_index": { "type": "integer" }
            }
        },
        "models.LoginReq": {
            "type": "object",
            "properties": {
                "user": { "type": "string" },
                "password": { "type": "string" }
            }
        },
        "models.Port": {
            "type": "object",
            "properties": {
                "number": { "type": "integer" },
                "state": { "type": "string" },
                "protocol": { "type": "string" },
                "service": { "type": "string" },
                "version": { "type": "string" },
                "host_id": { "type": "integer" },
                "is_baseline": { "type": "boolean" },
                "is_new": { "type": "boolean" }
            }
        },
        "models.RegisterReq": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "password": { "type": "string" }
            }
        },
        "models.Scan": {
            "type": "object",
            "properties": {
                "status": { "type": "string" },
                "start_time": { "type": "string" },
                "end_time": { "type": "string" },
                "hosts": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/models.Host" }
                }
            }
        },
        "models.Team": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "iprange": { "type": "string" },
                "tid": { "type": "string" },
                "description": { "type": "string" },
                "color": { "type": "string" },
                "hosts": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/models.Host" }
                }
            }
        },
        "models.TeamRequest": {
            "type": "object",
            "required": ["name", "iprange"],
            "properties": {
                "name": { "type": "string" },
                "iprange": { "type": "string" },
                "description": { "type": "string" },
                "color": { "type": "string" }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "active": { "type": "boolean" },
                "roles": {
                    "type": "array",
                    "items": { "type": "string" }
                },
                "uid": { "type": "string" }
            }
        },
        "models.UserReq": {
            "type": "object",
            "properties": {
                "active": { "type": "boolean" },
                "roles": {
                    "type": "array",
                    "items": { "type": "string" }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "NMAP Dashboard API",
	Description:      "API for NMAP Dashboard - track open ports across networks",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
